[package]
name = "glicol"
version = "0.13.0"
edition = "2021"
keywords = [
	"audio",
    "music",
	"DSP",
	"synth",
    "synthesizer"
]

license-file = "LICENSE"
description = "Glicol language main entry point."
repository = "https://github.com/chaosprint/glicol.git"
authors = ["Qichao Lan <chaosprint@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
use-samples = []
use-meta = []
bela = []

[dependencies]
petgraph = { version = "0.6",  features = ["stable_graph"] }
# dasp_graph = { path = "../dasp_graph" }
glicol_parser = { version = "0.13.0" } # , path="../parser"
glicol_synth = { version = "0.13.0", features = ["use-samples", "use-meta"]} #, path = "../synth" 
lcs-diff = "0.1.1"
pest = "2.1.3"
glicol_macros = "0.12.8"
hashbrown = "0.13.1"
# cargo build --target wasm32-unknown-unknown --release

[dev-dependencies]
gnuplot = "0.0.37"
# petgraph = { version = "0.6",  features = ["stable_graph"] }
cpal = "0.14.0"
anyhow = "1.0.63"